language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements.txt
services:
  - postgresql
addons:
  postgresql: "9.6"
before_script:
  - psql -c 'create database simpl;' -U postgres
script:
  - python runtests.py
