# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import simpl_users.managers


class Migration(migrations.Migration):

    dependencies = [
        ('simpl_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', simpl_users.managers.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='faculty',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='subscriber_code',
            field=models.CharField(blank=True, max_length=255, verbose_name='Subscriber Code'),
        ),
    ]
