# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-12 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpl_users', '0002_auto_20160421_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
