# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-12 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpl_users', '0003_user_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='student',
        ),
    ]
