# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-28 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpl_users', '0005_auto_20170227_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='canvas_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
