# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-28 21:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpl_users', '0006_auto_20170228_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='canvas_id',
            new_name='lms_id',
        ),
    ]
