# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-28 21:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpl_users', '0007_auto_20170228_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='lms_id',
            new_name='external_id',
        ),
    ]
